package com.bughowi.musikin;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.bumptech.glide.Glide;
import com.bumptech.glide.request.target.SimpleTarget;
import com.bumptech.glide.request.transition.Transition;

import java.util.Objects;

import de.hdodenhof.circleimageview.CircleImageView;

public class SongsDetail extends AppCompatActivity {

    private static final int[] songsAlbum = {
            R.drawable.album_different_world,
            R.drawable.album_avenged_sevenfold,
            R.drawable.album_pink_planet,
            R.drawable.album_voicenotes,
            R.drawable.album_fallen,
            R.drawable.album_whats_the_story,
            R.drawable.album_dangerous,
            R.drawable.album_i_dont_want_to_miss_a_thing,
            R.drawable.album_i_will_always_love_you,
            R.drawable.album_origins,
            R.drawable.album_doo_wops_hooligans,
            R.drawable.album_more_than_you_know,
            R.drawable.album_most_wanted,
            R.drawable.album_steelheart,
            R.drawable.album_21
    };

    private static final int[] songsArtist = {
            R.drawable.artist_alan_walker,
            R.drawable.artist_avenged_sevenfold,
            R.drawable.artist_pink_sweats,
            R.drawable.artist_charlie_puth,
            R.drawable.artist_evanescence,
            R.drawable.artist_oasis,
            R.drawable.artist_michael_jackson,
            R.drawable.artist_aerosmith,
            R.drawable.artist_whitney_houston,
            R.drawable.artist_imagine_dragons,
            R.drawable.artist_bruno_mars,
            R.drawable.artist_axwell_ingrosso,
            R.drawable.artist_wiz_khalifa,
            R.drawable.artist_steelheart,
            R.drawable.artist_adele
    };

    private static final String[] songsLyric = {
            "You were the shadow to my light\nDid you feel us\nAnother start\nYou fade away\nAfraid our aim is out of sight\nWanna see us\nAlive\n\nWhere are you now\nWhere are you now\nWhere are you now\nWas it all in my fantasy\nWhere are you now\nWere you only imaginary\nWhere are you now\n\nAtlantis\nUnder the sea\nUnder the sea\nWhere are you now\nAnother dream\nThe monsters running wild inside of me\n\nI'm faded\nI'm faded\nSo lost\nI'm faded\nThese shallow waters, never met\nWhat I needed\nI'm letting go\nA deeper dive\nEternal silence of the sea\nI'm breathing\nAlive\n\nWhere are you now\nWhere are you now\n\nUnder the bright\nBut faded lights\nYou set my heart on fire\nWhere are you now\nWhere are you now\n\nWhere are you now\nWhere are you now\n\nWhere are you now\nAtlantis\nUnder the sea\nUnder the sea\nWhere are you now\nAnother dream\nThe monsters running wild inside of me\nI'm faded\nI'm faded\nSo lost\nI'm faded",
            "A lonely road, crossed another cold state line\nMiles away from those I love purpose undefined\nWhile I recall all the words you spoke to me\nCan't help but wish that I was there\nAnd where I'd love to be, oh yeah\n\nDear God the only thing I ask of you is\nTo hold her when I'm not around\nWhen I'm much too far away\nWe all need that person who can be true to you\nBut I left her when I found her\nAnd now I wish I'd stayed\n'Cause I'm lonely and I'm tired\nI'm missing you again oh no\nOnce again\n\nThere's nothing here for me on this barren road\nThere's no one here while the city sleeps\nAnd all the shops are closed\nCan't help but think of the times I've had with you\nPictures and some\nmemories will have to help me through, oh yeah\n\nDear God the only thing I ask of you is to hold her when I'm not around\nWhen I'm much too far away\nWe all need that person who can be true to you\nI left her when I found her\nAnd now I wish I'd stayed\n'Cause I'm lonely and I'm tired\nI'm missing you again oh no\nOnce again\n\nSome search, never finding a way\nBefore long, they waste away\n\nI found you, something told me to stay\nI gave in, to selfish ways\nAnd how I miss someone to hold\nWhen hope begins to fade\n\nA lonely road, crossed another cold state line\nMiles away from those I love purpose undefined\n\nDear God the only thing I ask of you is to hold her when I'm not around\nWhen I'm much too far away\nWe all need the person who can be true to you\nI left her when I found her\nAnd now I wish I'd stayed\n'Cause I'm lonely and I'm tired\nI'm missing you again oh no\nOnce again",
            "Can I call you baby?\nCan you be my friend?\nCan you be my lover up until the very end?\nLet me show you love, oh, I don't pretend\nStick by my side even when the world is givin' in, yeah\n\nOh, oh, oh, don't\nDon't you worry\nI'll be there, whenever you want me\n\nI need somebody who can love me at my worst\nNo, I'm not perfect, but I hope you see my worth\n'Cause it's only you, nobody new, I put you first\nAnd for you, girl, I swear I'll do the worst\n\nIf you stay forever, let me hold your hand\nI can fill those places in your heart no else can\nLet me show you love, oh, I don't pretend, yeah\nI'll be right here, baby, you know I'll sink or swim\n\nOh, oh, oh, don't\nDon't you worry\nI'll be there, whenever you want me\n\nI need somebody who can love me at my worst\nNo, I'm not perfect, but I hope you see my worth, yeah\n'Cause it's only you, nobody new, I put you first (put you first)\nAnd for you, girl, I swear I'll do the worst\n\nI need somebody who can love me at my worst\nNo, I'm not perfect, but I hope you see my worth\n'Cause it's only you, nobody new, I put you first\nAnd for you, girl, I swear I'll do the worst\n",
            "Oh-oh, ooh\nYou've been runnin' round, runnin' round, runnin' round throwin' that dirt all on my name\n'Cause you knew that I, knew that I, knew that I'd call you up\nYou've been going round, going round, going round every party in L.A.\n'Cause you knew that I, knew that I, knew that I'd be at one, oh\n\nI know that dress is karma, perfume regret\nYou got me thinking 'bout when you were mine, oh\nAnd now I'm all up on ya, what you expect?\nBut you're not coming home with me tonight\n\nYou just want attention, you don't want my heart\nMaybe you just hate the thought of me with someone new\nYeah, you just want attention, I knew from the start\nYou're just making sure I'm never gettin' over you\n\nyou've been runnin' round, runnin' round, runnin' round throwing that dirt all on my name\n'Cause you knew that I, knew that I, knew that I'd call you up\nBaby, now that we're, now that we're, now that we're right here standing face-to-face\nYou already know, already know, already know that you won, oh\n\nI know that dress is karma (dress is karma), perfume regret\nYou got me thinking 'bout when you were mine (you got me thinking 'bout when you were mine)\nAnd now I'm all up on ya (all up on ya), what you expect? (oh baby)\nBut you're not coming home with me tonight (oh no)\n\nYou just want attention, you don't want my heart\nMaybe you just hate the thought of me with someone new\nYeah, you just want attention, I knew from the start\nYou're just making sure I'm never gettin' over you, oh\n\nWhat are you doin' to me, what are you doin', huh?\n(What are you doin'?)\nWhat are you doin' to me, what are you doin', huh?\n(What are you doin'?)\nWhat are you doin' to me, what are you doin', huh?\n(What are you doin'?)\nWhat are you doin' to me, what are you doin', huh?\n\nI know that dress is karma, perfume regret\nYou got me thinking 'bout when you were mine\nAnd now I'm all up on ya, what you expect?\nBut you're not coming home with me tonight\n\nYou just want attention, you don't want my heart\nMaybe you just hate the thought of me with someone new\nYeah, you just want attention, I knew from the start\nYou're just making sure I'm never gettin' over you (over you)\n\nWhat are you doin' to me? (hey) what are you doin', huh? (what are you doin', what?)\n(What are you doin', to me? What are you doin', huh?)\n(What are you doin', to me? What are you doin', huh?)\n(What are you doin' to me, what are you doin', huh?)\n",
            "How can you see into my eyes, like open doors\nLeading you down into my core\nWhere I've become so numb\nWithout a soul\nMy spirit's sleeping somewhere cold\nUntil you find it there and lead it back home\n\nWake me up inside (save me)\nCall my name and save me from the dark (wake me up)\nBid my blood to run (I can't wake up)\nBefore I come undone (save me)\nSave me from the nothing I've become\n\nNow that I know what I'm without\nYou can't just leave me\nBreathe into me and make me real\nBring me to life\n\nWake me up inside (save me)\nCall my name and save me from the dark (wake me up)\nBid my blood to run (I can't wake up)\nBefore I come undone (save me)\nSave me from the nothing I've become\n\nBring me to life\nI've been living a lie\nThere's nothing inside\nBring me to life\n\nFrozen inside without your touch\nWithout your love, darling\nOnly you are the life among the dead\n\nAll this time, I can't believe I couldn't see\nKept in the dark, but you were there in front of me\nI've been sleeping a thousand years it seems\nI've got to open my eyes to everything\nWithout a thought, without a voice, without a soul\nDon't let me die here\nThere must be something wrong, bring me to life\n\nWake me up inside (save me)\nCall my name and save me from the dark (wake me up)\nBid my blood to run (I can't wake up)\nBefore I come undone (save me)\nSave me from the nothing I've become\n\nBring me to life\nI've been living a lie\nThere's nothing inside\nBring me to life\n",
            "Slip inside the eye of your mind\nDon't you know you might find\nA better place to play\nYou said that you'd never been\nBut all the things that you've seen\nSlowly fade away\n\nSo I start a revolution from my bed\n'Cause you said the brains I had went to my head\nStep outside, summertime's in bloom\nStand up beside the fireplace\nTake that look from off your face\nYou ain't ever gonna burn my heart out\n\nAnd so Sally can wait\nShe knows it's too late\nAs we're walking on by\nHer soul slides away\nBut don't look back in anger\nI heard you say\n\nTake me to the place where you go\nWhere nobody knows\nIf it's night or day\nBut please don't put your life in the hands\nOf a rock and roll band\nWho'll throw it all away\n\nI'm gonna start a revolution from my bed\n'Cause you said the brains I had went to my head\nStep outside 'cause summertime's in bloom\nStand up beside the fireplace\nTake that look from off your face\n'Cause you ain't ever gonna burn my heart out\n\nAnd so Sally can wait\nShe knows it's too late\nAs she's walking on by\nMy soul slides away\nBut don't look back in anger\nI heard you say\n\nSo Sally can wait\nShe knows it's too late\nAs we're walking on by\nHer soul slides away\nBut don't look back in anger\nI heard you say\n\nSo Sally can wait\nShe knows it's too late\nAs she's walking on by\nMy soul slides away\nBut don't look back in anger\nDon't look back in anger\nI heard you say\nAt least not today\n",
            "There's a place in your heart\nAnd I know that it is love\nAnd this place it was brighter than tomorrow\nAnd if you really try\nYou'll find there's no need to cry\nIn this place you'll feel there's no hurt or sorrow\n\nThere are ways to get there\nIf you care enough for the living\nMake a little space\nMake a better place\n\nHeal the world\nMake it a better place\nFor you and for me, and the entire human race\nThere are people dying\nIf you care enough for the living\nMake a better place for you and for me\n\nIf you want to know why\nThere's love that cannot lie\nLove is strong\nIt only cares of joyful giving\nIf we try we shall see\nIn this bliss we cannot feel\nFear of dread, we stop existing and start living\n\nThen it feels that always\nLove's enough for us growing\nMake a better world\nSo make a better world\n\nHeal the world\nMake it a better place\nFor you and for me, and the entire human race\nThere are people dying\nIf you care enough for the living\nMake a better place for you and for me\n\nAnd the dream we were conceived in will reveal a joyful face\nAnd the world we once believed in will shine again in grace\nThen why do we keep strangling life\nWound this earth, crucify its soul?\nThough it's plain to see, this world is heavenly\nBe god's glow\n\nWe could fly so high\nLet our spirits never die\nIn my heart I feel you are all my brothers\nCreate a world with no fear\nTogether we cry happy tears\nSee the nations turn their swords into plowshares\n\nWe could really get there\nIf you cared enough for the living\nMake a little space\nTo make a better place\n\nHeal the world\nMake it a better place\nFor you and for me, and the entire human race\nThere are people dying\nIf you care enough for the living\nMake a better place for you and for me\nHeal the world\nMake it a better place\nFor you and for me, and the entire human race\nThere are people dying\nIf you care enough for the living\nMake a better place for you and for me\n\nHeal the world (heal the world)\nMake it a better place\nFor you and for me, and the entire human race\nThere are people dying\nIf you care enough for the living\nMake a better place for you and for me\n\nThere are people dying\nIf you care enough for the living\nMake a better place for you and for me\n",
            "I could stay awake just to hear you breathing\nWatch you smile while you are sleeping\nWhile you're far away and dreaming\nI could spend my life in this sweet surrender\nI could stay lost in this moment forever\nEvery moment spent with you is a moment I treasure\n\nDon't want to close my eyes\nI don't want to fall asleep\n'Cause I'd miss you baby\nAnd I don't want to miss a thing\n'Cause even when I dream of you\nThe sweetest dream will never do\nI'd still miss you baby\nAnd I don't want to miss a thing\n\nLying close to you, feeling your heart beating\nAnd I'm wondering what you're dreaming\nWondering if it's me you're seeing\nThen I kiss your eyes\nAnd thank God we're together\nAnd I just want to stay with you in this moment forever\nForever and ever\n\nI don't want to close my eyes\nI don't want to fall asleep\n'Cause I'd miss you baby\nAnd I don't want to miss a thing\n'Cause even when I dream of you\nThe sweetest dream will never do\nI'd still miss you baby\nAnd I don't want to miss a thing\n\nI don't want to miss one smile\nAnd I don't want to miss one kiss\nAnd I just want to be with you\n\nRight here with you, just like this\nAnd I just want to hold you close\nI feel your heart so close to mine\nAnd just stay here in this moment\nFor all the rest of time\nYeah, yeah, yeah, yeah, yeah\n\nDon't want to close my eyes\nDon't want to fall asleep\n'Cause I'd miss you baby\nAnd I don't want to miss a thing\n'Cause even when I dream of you (even when I dream)\nThe sweetest dream will never do\nI'd still miss you baby\nAnd I don't want to miss a thing\n\nI don't want to close my eyes\nI don't want to fall asleep\n'Cause I'd miss you baby\nAnd I don't want to miss a thing\n'Cause even when I dream of you\nThe sweetest dream will never do\nI'd still miss you baby\nAnd I don't want to miss a thing\n\nDon't want to close my eyes\nI don't want to fall asleep, yeah\nAnd I don't want to miss a thing\n",
            "If I should stay\nWell I would only be in your way\nAnd so I'll go, and yet I know\nI'll think of you each step of the way\n\nAnd I will always love you\nI will always love you\n\nBitter-sweet memories\nThat's all I'm taking with me\nGood-bye, please don't cry\n'Cause we both know that I'm not\nWhat you need\n\nBut I will always love you\nI will always love you\n\nAnd I hope life, will treat you kind\nAnd I hope that you have all\nThat you ever dreamed of\nOh I do wish you joy\nAnd I wish you happiness\nBut above all this\nI wish you love\nI love you\nI will always love you\n\nI, I will always, always love you\nI will always love you\nI will always love you\nI will always love you",
            "Oh, hush, my dear, it's been a difficult year\nAnd terrors don't prey on\nInnocent victims\nTrust me, darling, trust me darling\nIt's been a loveless year\nI'm a man of three fears\nIntegrity, faith and\nCrocodile tears\nTrust me, darling, trust me, darling\n\nSo look me in the eyes\nTell me what you see\nPerfect paradise\nTearing at the seams\nI wish I could escape\nI don't wanna fake it\nWish I could erase it\nMake your heart believe\n\nBut I'm a bad liar, bad liar\nNow you know\nNow you know\nI'm a bad liar, bad liar\nNow you know, you're free to go (go)\n\nDid all my dreams never mean one thing?\nDoes happiness lie in a diamond ring?\nOh, I've been askin'\nOh, I've been askin' for problems, problems, problems\nI wage my war, on the world inside\nI take my gun to the enemy's side\nOh, I've been askin' for (trust me, darling)\nOh, I've been askin' for (trust me, darling)\nProblems, problems, problems\n\nSo look me in the eyes\nTell me what you see\nPerfect paradise\nTearing at the seams\nI wish I could escape\nI don't wanna fake it\nWish I could erase it\nMake your heart believe\n\nBut I'm a bad liar, bad liar\nNow you know\nNow you know\nThat I'm a bad liar, bad liar\nNow you know, you're free to go\n\nI can't breathe, I can't be\nI can't be what you want me to be\nBelieve me, this one time\nBelieve me\n\nI'm a bad liar, bad liar\nNow you know\nNow you know\nThat I'm a bad liar, bad liar\nNow you know, you're free to go\n\nOh\nPlease believe me\nPlease believe me\n",
            "Oh, her eyes, her eyes\nMake the stars look like they're not shinin'\nHer hair, her hair\nFalls perfectly without her tryin'\nShe's so beautiful and I tell her everyday\nYeah, I know, I know\nWhen I compliment her, she won't believe me\nAnd it's so, it's so\nSad to think that she don't see what I see\nBut every time she asks me, \"Do I look okay?\"\nI say\n\nWhen I see your face\nThere's not a thing that I would change\n'Cause you're amazing\nJust the way you are\nAnd when you smile\nThe whole world stops and stares for a while\n'Cause girl, you're amazing\nJust the way you are\nYeah\n\nHer lips, her lips\nI could kiss them all day if she'd let me\nHer laugh, her laugh\nShe hates, but I think it's so sexy\nShe's so beautiful and I tell her everyday\nOh, you know, you know\nYou know I'd never ask you to change\nIf perfect's what you're searchin' for, then just stay the same\nSo don't even bother askin' if you look okay\nYou know I'll say\n\nWhen I see your face\nThere's not a thing that I would change\n'Cause you're amazing\nJust the way you are\nAnd when you smile\nThe whole world stops and stares for a while\n'Cause girl, you're amazing\nJust the way you are\n\nThe way you are\nThe way you are\nGirl, you're amazing\nJust the way you are\n\nWhen I see your face\nThere's not a thing that I would change\n'Cause you're amazing\nJust the way you are\nAnd when you smile\nThe whole world stops and stares for a while\n'Cause girl, you're amazing\nJust the way you are\nYeah\n",
            "I saw it coming, from miles away\nI better speak up if I got something to say\n'Cause it ain't over, until she sings\nYou had your reasons, you had a few\nBut you knew that I would go anywhere for you\n'Cause it ain't over, until she sings\n\nI just need to get it off my chest\nYeah, more than you know\nYeah, more than you know\nYou should know that baby you're the best\nYeah, more than you know\nYeah, more than you know\n\nYour good intentions are sweet and pure\nBut they can never tame a fire like yours\nNo it ain't over, until she sings\nRight where you wanted, down on my knees\nYou got me begging, pretty baby set me free\n'Cause it ain't over, until she sings\n\nCome a little closer, let me taste your smile\nUntil the morning lights\nAin't no going back the way you look tonight\nI see it in your eyes\n\nI just need to get it off my chest\nYeah, more than you know\nYeah, more than you know\nYou should know that baby you're the best\nYeah, more than you know\nYeah, more than you know\n\nYeah, more than you know\nYeah, more than you know\nYeah, more than you know\nYeah, more than you know\nYeah, more than you know\nYeah, more than you know\nYeah, more than you know\nYeah, more than you know\n\nI just need to get it off my chest\nYeah, more than you know\nYeah, more than you know\nYou should know that baby you're the best\nYeah, more than you know\nYeah, more than you know\n",
            "It's been a long day without you, my friend\nAnd I'll tell you all about it when I see you again\nWe've come a long way from where we began\nOh, I'll tell you all about it when I see you again\nWhen I see you again\n\nDamn, who knew?\nAll the planes we flew, good things we been through\nThat I'd be standing right here talking to you\n'Bout another path, I know we loved to hit the road and laugh\nBut something told me that it wouldn't last\nHad to switch up, look at things different, see the bigger picture\nThose were the days, hard work forever pays\nNow I see you in a better place (see you in a better place)\nUh\n\nHow can we not talk about family when family's all that we got?\nEverything I went through, you were standing there by my side\nAnd now you gon' be with me for the last ride\n\nIt's been a long day without you, my friend\nAnd I'll tell you all about it when I see you again (I'll see you again)\nWe've come a long way (yeah, we came a long way)\nFrom where we began (you know we started)\nOh, I'll tell you all about it when I see you again (I'll tell you)\nWhen I see you again\n\nFirst, you both go out your way and the vibe is feeling strong\nAnd what's small turned to a friendship, a friendship turned to a bond\nAnd that bond will never be broken, the love will never get lost\n(The love will never get lost)\nAnd when brotherhood come first, then the line will never be crossed\nEstablished it on our own when that line had to be drawn\nAnd that line is what we reached, so remember me when I'm gone\n(Remember me when I'm gone)\n\nHow can we not talk about family when family's all that we got?\nEverything I went through you were standing there by my side\nAnd now you gon' be with me for the last ride\n\nSo let the light guide your way, yeah\nHold every memory as you go\nAnd every road you take\nWill always lead you home, home\n\nIt's been a long day without you, my friend\nAnd I'll tell you all about it when I see you again\nWe've come a long way from where we began\nOh, I'll tell you all about it when I see you again\nWhen I see you again\n\nWhen I see you again (yeah, uh)\nSee you again (yeah, yeah, yeah)\n\nWhen I see you again\n",
            "She's gone\nOut of my life\nI was wrong\nI'm to blame\nI was so untrue\nI can't live without her love\n\nIn my life\nThere's just an empty space\nAll my dreams are lost\nI'm wasting away\nForgive me, girl\n\nLady, won't you save me?\nMy heart belongs to you\nLady, can you forgive me?\nFor all I've done to you\nLady, oh, lady\n\nShe's gone\nOut of my life\nOh, she's gone\nI find it so hard to go on\nI really miss that girl, my love\n\nCome back into my arms\nI'm so alone\nI'm begging you\nI'm down on my knees\nForgive me, girl\n\nLady, won't you save me?\nMy heart belongs to you\nLady, can you forgive me?\nFor all I've done to you\nLady, oh, lady\nOh, lady\n\nLady, won't you save me?\nMy heart belongs to you\nLady, can you forgive me?\nFor all I've done to you\n\nLady, oh, lady\nMy heart belongs to you\nLady, can you forgive me?\nFor all I've done to you\n",
            "I heard that you're settled down\nThat you found a girl and you're married now\nI heard that your dreams came true\nGuess she gave you things, I didn't give to you\nOld friend, why are you so shy?\nAin't like you to hold back or hide from the light\n\nI hate to turn up out of the blue, uninvited\nBut I couldn't stay away, I couldn't fight it\nI had hoped you'd see my face\nAnd that you'd be reminded that for me, it isn't over\n\nNever mind, I'll find someone like you\nI wish nothing but the best for you, too\n\"Don't forget me, \" I beg\nI remember you said\n\"Sometimes it lasts in love, but sometimes it hurts instead\"\n\"Sometimes it lasts in love, but sometimes it hurts instead\"\n\nYou know how the time flies\nOnly yesterday was the time of our lives\nWe were born and raised in a summer haze\nBound by the surprise of our glory days\n\nI hate to turn up out of the blue, uninvited\nBut I couldn't stay away, I couldn't fight it\nI had hoped you'd see my face\nAnd that you'd be reminded that for me, it isn't over\n\nNever mind, I'll find someone like you\nI wish nothing but the best for you, too\n\"Don't forget me, \" I begged\nI remember you said\n\"Sometimes it lasts in love, but sometimes it hurts instead\"\n\nNothing compares, no worries or cares\nRegrets and mistakes, they're memories made\nWho would have known how bittersweet this would taste?\n\nNever mind, I'll find someone like you\nI wish nothing but the best for you\n\"Don't forget me, \" I beg\nI remember you said\n\"Sometimes it lasts in love, but sometimes it hurts instead\"\n\nNever mind, I'll find someone like you\nI wish nothing but the best for you, too\n\"Don't forget me, \" I begged\nI remember you said\n\"Sometimes it lasts in love, but sometimes it hurts instead\"\n\"Sometimes it lasts in love, but sometimes it hurts instead\"\n"
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.songs_details);

        Objects.requireNonNull(getSupportActionBar()).hide();

        LinearLayout ivAlbumCover = findViewById(R.id.bg_songs_album_detail);
        TextView tvSongsTitle = findViewById(R.id.tv_songs_title_detail);
        TextView tvSongsArtist = findViewById(R.id.tv_songs_artist_detail);
        TextView tvSongsLyric = findViewById(R.id.tv_songs_lyric_detail);
        CircleImageView ivArtist = findViewById(R.id.iv_songs_artist_detail);

        int position = getIntent().getIntExtra("KEY BUAT GAMBAR", 0);
        tvSongsArtist.setText(getIntent().getStringExtra("KEY BUAT ARTIST"));
        tvSongsTitle.setText(getIntent().getStringExtra("KEY BUAT TITLE"));
        tvSongsLyric.setText(songsLyric[position]);
        Glide.with(this).load(songsArtist[position]).into(ivArtist);
        Glide.with(this).load(songsAlbum[position]).into(new SimpleTarget<Drawable>() {
            @Override
            public void onResourceReady(@NonNull Drawable resource, Transition<? super Drawable> transition) {
                ivAlbumCover.setBackground(resource);
            }
        });

    }
}